// <auto-generated/>
using System.Collections.Generic;

namespace CollectionDataReaderGenerator.Tests.TestData
{
    public partial struct PrimitiveTypesTableType
    {
        public static PrimitiveTypesTableTypeDataReader CreateDataReader(IEnumerable<PrimitiveTypesTableType> source)
        {
            return new PrimitiveTypesTableTypeDataReader(source);
        }

        public const string SqlText = @"
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'Generated')
BEGIN
    EXEC('CREATE SCHEMA Generated');
END;
GO

IF EXISTS (
    SELECT * FROM sys.types 
    WHERE is_table_type = 1 
    AND name = N'PrimitiveTypesTableType'
    AND schema_id = SCHEMA_ID(N'Generated')
)
BEGIN
    DECLARE @sql NVARCHAR(MAX) = N'DROP TYPE Generated.PrimitiveTypesTableType;';
    EXEC sp_executesql @sql;
END;
GO

CREATE TYPE Generated.PrimitiveTypesTableType AS TABLE
(
    Qwerty uniqueidentifier,
    BooleanColumn bit,
    StringColumn nvarchar(20),
    DecimalColumn decimal(18, 5),
    DoubleColumn float,
    FloatColumn real,
    IntColumn int,
    LongColumn bigint,
    ShortColumn smallint,
    DateTimeColumn datetime2
);
GO

";

        public const string TableTypeName = "Generated.PrimitiveTypesTableType";
    }
}