// <auto-generated/>
using System.Collections.Generic;

namespace CollectionDataReaderGenerator.Tests.TestData
{
    public partial struct PrimitiveTypesTableType
    {
        public static PrimitiveTypesTableTypeDataReader CreateDataReader(IEnumerable<PrimitiveTypesTableType> source)
        {
            return new PrimitiveTypesTableTypeDataReader(source);
        }

        public static PrimitiveTypesTableTypeSqlRecordEnumerator CreateSqlRecordEnumerator(IEnumerable<PrimitiveTypesTableType> source)
        {
            return new PrimitiveTypesTableTypeSqlRecordEnumerator(source);
        }

        public const string CreateTableTypeSqlText = @"
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'Generated')
BEGIN
    EXEC('CREATE SCHEMA Generated');
END;

IF EXISTS (
    SELECT * FROM sys.types
    WHERE is_table_type = 1
    AND name = N'PrimitiveTypesTableType'
    AND schema_id = SCHEMA_ID(N'Generated')
)
BEGIN
    DECLARE @sql NVARCHAR(MAX) = N'DROP TYPE Generated.PrimitiveTypesTableType;';
    EXEC sp_executesql @sql;
END;

CREATE TYPE Generated.PrimitiveTypesTableType AS TABLE
(
    Qwerty uniqueidentifier,
    BooleanColumn bit,
    StringColumn nvarchar(20),
    StringColumn2 varchar(10),
    DecimalColumn decimal(18, 5),
    DoubleColumn float,
    FloatColumn real,
    IntColumn int,
    LongColumn bigint,
    ShortColumn smallint,
    DateTimeColumn datetime2
);
";

        public const string TableTypeName = "Generated.PrimitiveTypesTableType";

        public const string TempTableName = "#PrimitiveTypesTableType";

        public const string CreateTempTableSqlText = @"
CREATE TABLE #PrimitiveTypesTableType (
    Qwerty uniqueidentifier,
    BooleanColumn bit,
    StringColumn nvarchar(20),
    StringColumn2 varchar(10),
    DecimalColumn decimal(18, 5),
    DoubleColumn float,
    FloatColumn real,
    IntColumn int,
    LongColumn bigint,
    ShortColumn smallint,
    DateTimeColumn datetime2
);
";
    }
}